replicaCount: 1
image:
  repository: ghcr.io/nikhil-kumar-k-s/devops-starter
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pat   # change to your secret name if you create one

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: "devops-starter.local"

resources: {}
