name: Build and publish to GHCR

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: devops-starter
  REGISTRY: ghcr.io/nikhil-kumar-k-s   # change here if you want a different namespace

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_REPO: ${{ steps.set-image.outputs.IMAGE_REPO }}
      IMAGE_TAG: ${{ steps.set-image.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image info
        id: set-image
        run: |
          echo "IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          IMAGE=${{ steps.set-image.outputs.IMAGE_REPO }}:${{ steps.set-image.outputs.IMAGE_TAG }}
          echo "Building ${IMAGE}"
          docker build -t "${IMAGE}" .

      - name: Push image to GHCR
        run: |
          IMAGE=${{ steps.set-image.outputs.IMAGE_REPO }}:${{ steps.set-image.outputs.IMAGE_TAG }}
          echo "Pushing ${IMAGE}"
          docker push "${IMAGE}"

      - name: Publish CI outputs for deployment
        run: |
          mkdir -p ci-output
          echo "${{ steps.set-image.outputs.IMAGE_REPO }}" > ci-output/IMAGE_REPO.txt
          echo "${{ steps.set-image.outputs.IMAGE_TAG }}"  > ci-output/IMAGE_TAG.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-output
          path: ci-output/
