name: Build and publish to GHCR

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: devops-starter
  REGISTRY: ghcr.io/nikhil-kumar-k-s

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_REPO: ${{ steps.set-image.outputs.IMAGE_REPO }}
      IMAGE_TAG:  ${{ steps.set-image.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image outputs
        id: set-image
        run: |
          echo "IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t \
            ${{ steps.set-image.outputs.IMAGE_REPO }}:${{ steps.set-image.outputs.IMAGE_TAG }} .

      - name: Push image
        run: |
          docker push \
            ${{ steps.set-image.outputs.IMAGE_REPO }}:${{ steps.set-image.outputs.IMAGE_TAG }}

      - name: Log final image
        run: |
          echo "Pushed image:"
          echo "${{ steps.set-image.outputs.IMAGE_REPO }}:${{ steps.set-image.outputs.IMAGE_TAG }}"
