name: Build and publish to GHCR

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: devops-starter
  REGISTRY: ghcr.io/${ github.repository_owner }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${ github.actor }
          password: ${ secrets.GITHUB_TOKEN }

      - name: Build image
        run: |
          IMAGE=${REGISTRY}/${IMAGE_NAME}:${github.sha}
          docker build -t $IMAGE .

      - name: Push image
        run: |
          IMAGE=${REGISTRY}/${IMAGE_NAME}:${github.sha}
          docker push $IMAGE

      - name: Output image
        run: echo "IMAGE=${REGISTRY}/${IMAGE_NAME}:${github.sha}"
